name: Update awesome-stars

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  awesome-stars:
    name: update awesome-stars
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - run: pip install starred
      - name: Update star list
        run: starred --username ${{ github.repository_owner }} --sort --token ${{ secrets.GITHUB_TOKEN }} > README.md
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Update awesome stars"
      - name: Pull changes
        run: git pull -r
      - name: Push changes
        uses: ad-m/github-push-action@b007e7b818e33b04afd056e4c4b57ba917145d7a
        with:
          github_token: ${{ secrets.GH_TOKEN }}
